local Main = require()
local Vars = require()
local Functions = require()
local GIT = require()
local WEB = require()
local Minix34 = require()

--// Core Tables

local Core = {}
local Functions = {}
local Vars = {}
local GIT = {}
local WEB = {}
local Main = {}
local Output = {}
local Errors = {}
local Warnings = {}
local UnidentifiedPrints = {}

--// UserTablesManagement

local Users = {}
local UsersError = {}
local UsersWarns = {}
local UsersCore = {}
local UsersUI = {}

--// User Tables

--// Examples:

Users.User1 = {
	Name = "",
	SecondName = "",
	Age = "",
	DateOfBirth = "",
	Details = {
		FavThings = "",
		Hobbys = "",
		Clubs = "",
		Adress = "",
		HouseNumber = "",
		ComputerVersion = "",
		ComputerType = "",
		Skills = "",
		Hates = "",
		RobloxJoinDate = "",
		CoreDetails = {
			TokenID = "",
			UserID = "",
		}
	}
}


